Feature/spp 826/adjusted value
ONSdigital/takeon-ui pull request #117
Opened 2020-12-09 10:47 UTC by mattprice-28

# Description
New adjusted response column added to formview html and python script updated to retrieve new data and add it into the array for display
https://collaborate2.ons.gov.uk/jira/browse/SPP-826

# How to test?
Changes are viewable in the spp826 environment
Have included a sql insert statement in the database repo
https://github.com/ONSdigital/takeon-database/blob/feature/SPP-826/AdjustedValue/story_updates/SPP-826-Adjusted-Response-Value.sql
Only added data for reference 12345678000, script can be used in pgadmin to add responses for other responses if required
New column is observable on all forms, adjusted values will appear as a label (therefore uneditable) where data exists in the database

# Links

2020-12-10 09:58 UTC, dllmorgan submitted a review, later dismissed

2020-12-10 09:58 UTC, dllmorgan commented on app/utilities/combine_data.py
> +    question_data['adjustedresponse'] = adjusted_response
Couldn't lines 7 and 10 be replaced with:
`question_data['adjustedresponse'] = form_data['view_form_responses'][index]['adjustedresponse']`

2020-12-10 13:37 UTC, mattprice-28 commented on app/utilities/combine_data.py
> +    question_data['adjustedresponse'] = adjusted_response
Done

2020-12-10 17:13 UTC, ranjit-das commented
Tested by modifying the AdjustedResponse value to 'null' in the database. Then searching the same reference, period, survey from UI has failed with - 'Sorry, there is a problem with the service'. Update statement used in database -
update dev01.response
set AdjustedResponse = null
where reference = '12345678000'
and period = '201801'
and Survey = '999A'
and questionCode = '1000'

2020-12-11 07:52 UTC, sivagudur requested changes

2020-12-11 07:52 UTC, sivagudur commented on app/utilities/combine_data.py
> +    question_data['adjustedresponse'] = form_data['view_form_responses'][index]['adjustedresponse']
@rhiGriff @mattprice-28  do we need this DateAdjustment parameter in UI form Save submit? I mean as we are not going to Save in Business layer(it is read only field and populated by Validation pipeline) Matt removed this parameter from Save database function during yesterday's review comments. Thanks.

2020-12-14 09:35 UTC, sivagudur approved these changes

2020-12-17 08:39 UTC, RyanAldy approved these changes

2020-12-17 09:32 UTC, sivagudur approved these changes

2020-12-17 09:32 UTC, RyanAldy approved these changes

2020-12-17 09:41 UTC, merged