Validationerror
ONSdigital/takeon-ui pull request #155
Opened 2021-09-13 12:28 UTC by sufyaniqbal

# Description
change to allow validation to work again

# How to test?
env: spp2824 
trigger validations

# Links
https://collaborate2.ons.gov.uk/jira/browse/SPP-3928

2021-09-13 12:32 UTC, mattprice-28 approved these changes

2021-09-14 06:38 UTC, rhiGriff approved these changes
2 questions around why this has changed

2021-09-14 06:38 UTC, rhiGriff commented on app/templates/view_form/BaseFormView.html
> +                        <a href="#tabId1" class="tab tab--row" data-ga="click" data-ga-category="tabs" data-ga-action="Show: Current Data" data-ga-label="Show: Current Data" aria-selected="true">Curr
Why have these been changed back to data? These were changed to response as per story SPP-830: https://collaborate2.ons.gov.uk/jira/browse/SPP-830

2021-09-14 06:38 UTC, rhiGriff commented on app/templates/view_form/BaseFormView.html
> +                        <a href="#tabId2" class="tab tab--row" data-ga="click" data-ga-category="tabs" data-ga-action="Show: Historic Data" data-ga-label="Show: Historic Data" aria-selected="false">H
Why have these been changed back to data? These were changed to responses as per story SPP-830: https://collaborate2.ons.gov.uk/jira/browse/SPP-830

2021-09-14 06:47 UTC, rhiGriff requested changes
Questions around change

2021-09-14 07:53 UTC, rhiGriff approved these changes
Reasonings make sense as lon as display to users useres response / responses all good

2021-09-14 09:55 UTC, merged